FROM node:18.13.0 AS build
WORKDIR /app
RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
# npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"] # for some reason doesnt work unless given 0.0.0.0