FROM node:18.13.0
WORKDIR /app
RUN npm install -g @angular/cli
RUN ng add @angular/material
COPY package*.json ./
RUN npm install
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]